# Generated by Django 4.1.7 on 2023-03-15 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ForgotPassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(max_length=6, verbose_name='OTP')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
